// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_auth_logout from "./routes/api/auth/logout.ts";
import * as $api_auth_me from "./routes/api/auth/me.ts";
import * as $api_auth_refresh from "./routes/api/auth/refresh.ts";
import * as $api_graphql from "./routes/api/graphql.ts";
import * as $auth_change_password from "./routes/auth/change_password.tsx";
import * as $auth_signin from "./routes/auth/signin.tsx";
import * as $auth_signup from "./routes/auth/signup.tsx";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $settings from "./routes/settings.tsx";
import * as $ChangePasswordForm from "./islands/ChangePasswordForm.tsx";
import * as $QueryProvider from "./islands/QueryProvider.tsx";
import * as $SignInForm from "./islands/SignInForm.tsx";
import * as $SignUpForm from "./islands/SignUpForm.tsx";
import * as $UserSettingsForm from "./islands/UserSettingsForm.tsx";
import * as $Workspace from "./islands/Workspace.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/auth/logout.ts": $api_auth_logout,
    "./routes/api/auth/me.ts": $api_auth_me,
    "./routes/api/auth/refresh.ts": $api_auth_refresh,
    "./routes/api/graphql.ts": $api_graphql,
    "./routes/auth/change_password.tsx": $auth_change_password,
    "./routes/auth/signin.tsx": $auth_signin,
    "./routes/auth/signup.tsx": $auth_signup,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
    "./routes/settings.tsx": $settings,
  },
  islands: {
    "./islands/ChangePasswordForm.tsx": $ChangePasswordForm,
    "./islands/QueryProvider.tsx": $QueryProvider,
    "./islands/SignInForm.tsx": $SignInForm,
    "./islands/SignUpForm.tsx": $SignUpForm,
    "./islands/UserSettingsForm.tsx": $UserSettingsForm,
    "./islands/Workspace.tsx": $Workspace,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
