//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

use sea_orm::entity::prelude::*;

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "token_kind")]
pub enum TokenKind {
    #[sea_orm(string_value = "email_verification")]
    EmailVerification,
    #[sea_orm(string_value = "password_reset")]
    PasswordReset,
}
